# Generated by Django 5.2 on 2025-04-18 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_houses', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StreetViewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('house_count', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('street_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='house_counter.streetsearch')),
            ],
        ),
    ]
