# Generated by Django 5.2 on 2025-04-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streetsearch',
            old_name='total_houses',
            new_name='total_trees',
        ),
        migrations.RenameField(
            model_name='streetviewimage',
            old_name='house_count',
            new_name='tree_count',
        ),
    ]
