# Generated by Django 5.2 on 2025-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_counter', '0002_rename_total_houses_streetsearch_total_trees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetsearch',
            name='processing_message',
            field=models.CharField(blank=True, default='Initializing search...', max_length=255, null=True),
        ),
    ]
