# Generated by Django 5.2 on 2025-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_counter', '0003_streetsearch_processing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetsearch',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streetsearch',
            name='end_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streetsearch',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streetsearch',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
